---

- name: run containers
  hosts: all
  become: true

  tasks:
  - name: copy docker file
    copy:
      src: docker-compose.yml
      dest: docker-compose.yml
  - name: list files
    shell:
      cmd: ls
  - name: dockercompose
    docker_compose:
      project_src: .
      state: present
